// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsStg.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXEqsoH58JbwEEiXtggfk8KTWTwbMV-k',
    appId: '1:445639197713:android:f94078320bb6124d625db0',
    messagingSenderId: '445639197713',
    projectId: 'flavors-firebase-demo-stg',
    storageBucket: 'flavors-firebase-demo-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qkMWRUtKMm-WnvWnTAez1wRvxsmZrag',
    appId: '1:445639197713:ios:1e958f621d2d1b3e625db0',
    messagingSenderId: '445639197713',
    projectId: 'flavors-firebase-demo-stg',
    storageBucket: 'flavors-firebase-demo-stg.appspot.com',
    iosClientId:
        '445639197713-0012am11nv6amghnc0seaesdjno4impk.apps.googleusercontent.com',
    iosBundleId: 'dev.mixin27.flavorsFirebase.stg',
  );
}
